=== alanpassos/integration-UFS/Iury/Tecnologias de Desenvolvimento para Internet/XML/exeSlide.xsd
<xs:element name="catalog" type="cd">
  <xs:complexType name="cd">
    <xs:sequence>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="artist" type="xs:string"/>
      <xs:element name="country" type="xs:string"/>
      <xs:element name="company" type="xs:string"/>
      <xs:element name="price" type="xs:decimal"/>
      <xs:element name="year" type="xs:string"/>
    </xs:sequence>
  </xs:complexType:

=== alanpassos/integration-UFS/Iury/Tecnologias de Desenvolvimento para Internet/XML/exeSlide.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Se o documento referenciar um arquido DTD -->
<!DOCTYPE exeSlide SYSTEM "exeSlide.dtd">


<!--   Se o documento referenciar um arquivo xsd -->
<catalog
  xmlns="exeSlide"
  xmlns:xsi="exeSlide"
  xsi:schemaLocation="exeSlide.xsd exeSlide.xsd">
  <cd>
    <title>Empire Burlesque</title>
    <artist>Bob Dylan</artist>
    <country>USA</country>
    <company>Columbia</company>
    <price>10.90</price>
    <year>1985</year>
  </cd>
</catalog>
